name: Rolfin.Blazor.Components - Release

on:
  workflow_run:
    workflows: ["Rolfin.Blazor.Components - CI"]
    branches: [ main ]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 'net7.0-windows10.0.19041.0'
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Rolfin.Blazor.Components/Rolfin.Blazor.Components.csproj
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
